### ISSUE TITLE
Support for git-on-windows == 2.13.3

### ISSUE THREAD

**Issue by theldoria** [magit/ssh-agency#10]
I tried to upgrade to Git-for-windows v2.13.3-64 bit. There are some changes regarding the ssh agent. For example, the tools `ssh-add` and `ssh-agent` are not under `/usr/bin/`. I could not successfully find the tool `git-gui--askpass`.

Could you please adapt your very useful packet to those changes?

**Comment by npostavs** [comment]
I've downloaded v.2.13.3 and the executables appear to be in the same place, but that particular version seems not to support upper case git aliases (although 2.14.0 does work fine). Should be fixed by #11.
