### ISSUE TITLE
ssh-agency-find-agent don't setup correctly SSH_AUTH_SOCK when using gnome-keyring-daemon

### ISSUE THREAD

**Issue by ryukinix** [magit/ssh-agency#12]
![image](https://user-images.githubusercontent.com/7642878/31452504-7ce33a5c-ae85-11e7-9af4-748a34d4fbfd.png)

As you see the `SSH_AUTH_SOCK` is different, the current SSH_AUTH_SOCK running from the system is the agent with the keys, but ssh-agency didn't see that for some reason and start a new ssh agent without keys on emacs startup.

For some reason, the ssh-agency-ensure seems not sufficient to find my ssh-agent. That's is a really weird, since I didn't see any upgrade on ssh-agency... so I'm wondering if was something on the system.

How can I debug that?

```
Emacs version: 25.3.1
System: Arch Linux
Kernel: Linux starfox 4.9.44-1-lts #1 SMP Wed Aug 23 20:16:47 UTC 2017 x86_64 GNU/Linux
ssh-agency: 20170807.1152
DE: XFCE
```

**Comment by npostavs** [comment]
What agents do you have running? Try `pgrep -a ssh-agent` from the shell.
What are the values of `SSH_AGENT_PID` in the shell and Emacs?

It's been a while since I've looked at ssh-agency.el, but it looks like it expects the socket file to have a name of the form `/tmp/ssh-xxxxx/agent.nnnn`, but your shell has `/run/user/1000/keyring/ssh` which doesn't follow this. Maybe that is some new behaviour of ssh?

**Comment by ryukinix** [comment]
![image](https://user-images.githubusercontent.com/7642878/31455703-e0d228ee-ae8e-11e7-9dbf-92291348dc99.png)

This seems weird. So then `ssh-agency-find-agent` find the ssh-agent, but didn't setup correctly (for me) the sock?

Well, I'm just using the `/usr/bin/gnome-keyring-daemon --start --components=ssh` on startup, to handle the keyring stuff.

**Comment by ryukinix** [comment]
Probably if I set hardcoded the SSH_AUTH_SOCK after calling ssh-agency this can work... but will be not nice.

**Comment by npostavs** [comment]
It seems this `/run/user/1000/keyring/ssh` is a gnome-keyring thing. Does gnome-keyring **use** ssh-agent, or **replace** it?

**Comment by ryukinix** [comment]
Well, setting `SSH_AUTH_SOCK` hardcoded worked, as expected. So then I was wrong about `ssh-agency`are opening more than one ssh-agent. This is not happening. What happens is: my setup weirdly set the SSH_AUTH_SOCK on another place which `ssh-agency` don't handles it, because I'm relying to my SSH_AUTH_SOCK be defined by `gnome-keyring-daemon`.

But I have a bigger problem here, since I use a emacs daemon that start before my user login. That way the SSH_AUTH_SOCK is not created yet when emacs start and call `ssh-agency-ensure`. But I already fix that (partially) with a workaround. I set a hardcoded variable on var config of emacs daemon:
```
❯ cat /etc/conf.d/emacs.lerax
export LANG=en_US.utf8
export USER=lerax
export HOME=/home/lerax
export SHELL=/usr/bin/zsh
export SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
 ```

That way the SSH_AUTH_SOCK will be visible when the daemon `emacs.lerax` start (my OpenRC daemon service for emacs). The tricky part is here on init of emacslisp:

```emacs-lisp
(when (executable-find ssh-agency-agent-executable)
  ;; this will not work if the is defined SSH_AUTH_SOCK but was not opened yet
  ;; On my setup for Linux I rely on gnome-keyring to open this shit on XFCE startup
  ;; so then try running without login with X and XFCE, this will not work 
  ;; since gnome-keyring for ssh is triggered only XFCE session startup
  (let ((hardcoded-auth (getenv "SSH_AUTH_SOCK")))
    (ssh-agency-ensure)
    (when hardode-env ;; if hardcoded was defined
        (setenv "SSH_AUTH_SOCK_BACK" (getenv "SSH_AUTH_SOCK"))
        (setenv "SSH_AUTH_SOCK" hardcode-auth))))
```

Would be nice if something more easy was provided by `ssh-agency`, but since it's seems a very unusual setup, maybe this can be such useless. 

Anyway, thanks for the support @npostavs on debugging. Ideas for debugging is always useful.

**Comment by ryukinix** [comment]
I tested here @npostavs before you ask, if a `ssh-agent` is not running, `gnome-keyring-daemon` will start one. If already exists a instance, will no create another (there is no replace). So the answer is: `use` if exists.

Since my emacs daemon start before `gnome-keyring-daemon` stuff, in general `ssh-agency` start the `ssh-agent` first (on boot) and `gnome-keyring` will use that same agent with opening on SSH_AUTH_SOCK on login using a new variable.

**Comment by npostavs** [comment]
According to https://wiki.gnome.org/Projects/GnomeKeyring/Ssh, gnome-keyring comes with its own ssh-agent:
> Gnome Keyring includes an SSH agent which integrates with the gnome-keyring and user login for its passwords. It can also use the main PKCS#11 private key store.

> Gnome Keyring will set the SSH_AUTH_SOCK environment variable when it starts up. 

> As a system distributor or a user, if you use another SSH agent (such as the ssh-agent included with OpenSSH), you may want to disable the SSH agent in GNOME

**Comment by ryukinix** [comment]
I don't have sure about that. The `gnome-keyring` package files is just that on my system: http://ix.io/B7w. And I didn't find another ssh-agent.

**Comment by ryukinix** [comment]
Maybe is a embedded `ssh-agent` on one of that binaries? I'm thinking how about my setup worked since `gnome-keyring` supposedly replaces the `ssh-agent` called by `ssh-agency`.

**Comment by npostavs** [comment]
It says

> If you're starting gnome-keyring manually or from a script you can use the --components option to exclude starting up the SSH support.
>
>     $ gnome-keyring-daemon --components keyring,pkcs11

So I guess gnome-keyring-daemon has something equivalent to ssh-agent inside it.

**Comment by ryukinix** [comment]
Interesting. Well, my setup is working for while, but I think we should that issue opened since we not have a definitive solution for that yet. If someone get trouble using `gnome-keyring` and `ssh-agency`, we already know some reasons for this. I have another computer which this same setup and is the same behavior too. I was always wondering why I need to auth always again on emacs, but not on terminal... and is because of that.

**Comment by ryukinix** [comment]
Related: https://unix.stackexchange.com/questions/315004/where-does-gnome-keyring-set-ssh-auth-sock/319796

On my another machine the SSH_AUTH_SOCK is random :/ so the above solution will not work: 
![image](https://user-images.githubusercontent.com/7642878/31462071-bc3afbba-aea1-11e7-9f68-29f1cfcbc471.png)
 
So much unnecessary mess...

**Comment by npostavs** [comment]
> But I have a bigger problem here, since I use a emacs daemon that start before my user login. That way the SSH_AUTH_SOCK is not created yet when emacs start and call `ssh-agency-ensure`.

Are you calling `ssh-agency-ensure` from your init.el? That shouldn't be needed, as by default ssh-agency adds it to `magit-credential-hook` so that it will only be called when you push/pull with magit.

---

> On my another machine the SSH_AUTH_SOCK is random :/ so the above solution will not work:

Okay, so far we have

- the traditional `ssh-agent` location: `/tmp/ssh-xxxxx/agent.NNN` (ref https://man.openbsd.org/ssh-agent "the default is `$TMPDIR/ssh-XXXXXXXXXX/agent.<ppid>`.")
- the `gnome-keyring-daemon` location: `/run/user/[uid]/keyring/ssh` (ref https://unix.stackexchange.com/questions/315004/where-does-gnome-keyring-set-ssh-auth-sock/319796)
- the new (3.18+) `gnome-keyring-daemon` location: `~/.cache/keyring-XXXXX/ssh` (ref https://unix.stackexchange.com/a/319796/47926 "As of Gnome 3.18, the socket appears to be stored in `~/.cache/keyring-(some random string)/ssh`")

We could 
- add these specific locations to search in
- try looking at open sockets via `netstat` or `ss` (POSIX/GNU specific)
- try to grab a valid `SSH_AUTH_SOCK` value with ` initctl get-env foo` (seems to be upstart specific, ref http://upstart.ubuntu.com/cookbook/#initctl-get-env)

I think we will end up with "all of the above".

**Comment by ryukinix** [comment]
> Are you calling ssh-agency-ensure from your init.el? That shouldn't be needed, as by default ssh-agency adds it to magit-credential-hook so that it will only be called when you push/pull with magit.

Yes, you are right. Maybe I should remove that later.

> the new (3.18+) gnome-keyring-daemon location: ~/.cache/keyring-XXXXX/ssh (ref https://unix.stackexchange.com/a/319796/47926 "As of Gnome 3.18, the socket appears to be stored in ~/.cache/keyring-(some random string)/ssh")

I saw that, but this is funny. On both systems I use 3.20 and one of them use `~/.cache/keyring-XXXXX/ssh` and the other `/run/user/[uid]/keyring/ssh`, but I don't have a clue the reason is different. I don't find any config file about that. I didn't find any documentation of defining the `--control-directory` param through the inicialization of pam modules, which call the gnome-keyring after a sucessulf login on my display manager (`/etc/pam.d/lightdm`). If I can setup that, at least my workaround will work on 
 both machines.

> add these specific locations to search in

This will be nice. But seems much complicated in the case of `~/.cache/keyring-(random)/ssh`. But I would like if `ssh-agency` search at least sockets opened on `/run/user/[uid]/keyring/ssh`. This will cut at least half of my problems.

> try looking at open sockets via netstat or ss (POSIX/GNU specific)

I like that approach, seems more robust. But the socket port is not constant, right? So we should filter by `ssh` keyword?
```
❯ netstat | grep ssh
tcp        0      0 starfox:46478           lb-192-30-253-112-i:ssh ESTABLISHED
unix  3      [ ]         STREAM     CONNECTED     1163536  /run/user/1000/keyring/ssh
```

> try to grab a valid SSH_AUTH_SOCK value with initctl get-env foo (seems to be upstart specific, ref http://upstart.ubuntu.com/cookbook/#initctl-get-env)

Unfortunately I don't have `initctl` on my distro, seems some specific of `ubuntu`. That idea seems not very good for this reason. I have a `Arch Linux` on my main computer (PC) and a `Manjaro` on notebook, both using OpenRC, so I think we should not rely on existence of specific things of init systems.

**Comment by npostavs** [comment]
Try out the patch in #12. My current machine has only `ss`, not `netstat`, so only the former is tested, but in theory it should find all the sockets now. :)

**Comment by ryukinix** [comment]
Awesome job!!! Really thank you. I'll test in soon! I hope this can be merged.

**Comment by npostavs** [comment]
> I'll test in soon!

Ping?

**Comment by ryukinix** [comment]
Sorry for the delay, I was busy with university stuff. I don't have access to my notebook right now, but I tested on the user case when SSH_AUTH_SOCK points to `/var/run/1000/keyring/ssh` and works pretty fine (on my desktop). 

Thanks for supporting that!

**Comment by npostavs** [comment]
> I don't have access to my notebook right now, but I tested on the user case when SSH_AUTH_SOCK points to /run/user/1000/keyring/ssh and works pretty fine (on my desktop).

Do both of your machines have `netstat` but not `ss`? The location of the socket isn't really important (apart from not being the default `$TMPDIR/ssh-XXXXXXXXXX/agent.<ppid>`).

**Comment by ryukinix** [comment]
```
~
❯ which netstat
/usr/bin/netstat

~
❯ which ss
/usr/bin/ss

~
❯ 

```

Yes.

**Comment by npostavs** [comment]
Okay, could you test with the `ss` code disabled, e.g., 

Change this bit:

    ,@(when (executable-find "ss")

to

    ,@(when nil ;; (executable-find "ss")

**Comment by ryukinix** [comment]
Sorry, actually this is not working properly. Not even with `ss` or `netstat`. I forgot to disable all my scripts before testing that, so was working because another reason.

After remove the hardcoded SSH_AUTH_SOCK and my init scripts that handles that, I restarted the emacs, re-eval the ssh-agency version on PR and I get back on the initial stage. A new PID agent is created with another SSH_AUTH_SOCK.

![image](https://user-images.githubusercontent.com/7642878/31867007-2aa083c6-b75e-11e7-9470-6db11c139678.png)

**Comment by ryukinix** [comment]
Maybe I setup something wrong? Is something info of debug I can provide for you?

**Comment by npostavs** [comment]
What is the output from running `netstat -f unix` at the shell?

**Comment by npostavs** [comment]
also output of `ss --no-header --listening --family=unix` would be of interest.

**Comment by ryukinix** [comment]
HMM

For first: 
```
❯ netstat -f unix
netstat: feature `AF BLUETOOTH' not supported.
Please recompile `net-tools' with newer kernel source or full configuration.
``
I don't understand exactly the reason of that output. How I can disable AF BLUETOOTH?

On second:
```
u_str  LISTEN     0      128    /tmp/.X11-unix/X0 13600                 * 0                    
u_str  LISTEN     0      128    @/tmp/dbus-7ZKKyHOKvF 13732                 * 0                    
u_str  LISTEN     0      64     /home/lerax/.ssh/sockets/git@github.com-22.BEC1EBDvHPUX0C8p 5850527               * 0                    
u_str  LISTEN     0      128    /tmp/ssh-84zFuX3KOqmG/agent.2732 12819                 * 0                    
u_str  LISTEN     0      128    /run/syslog-ng.ctl 12314                 * 0                    
u_str  LISTEN     0      5      /tmp/emacs1000/server 6309590               * 0                    
u_str  LISTEN     0      128    @/tmp/.ICE-unix/3207 22226                 * 0                    
u_str  LISTEN     0      128    @/tmp/.X11-unix/X0 13599                 * 0                    
u_dgr  UNCONN     0      0      /dev/log 12329                 * 0                    
u_str  LISTEN     0      5      /home/lerax/.dropbox/command_socket 24652                 * 0                    
u_str  LISTEN     0      128    /tmp/.ICE-unix/3207 22227                 * 0                    
u_str  LISTEN     0      5      /tmp/.esd-1000/socket 23501                 * 0                    
u_str  LISTEN     0      128    /tmp/ssh-tQDtBOJjg7Hu/agent.20741 5974788               * 0                    
u_str  LISTEN     0      5      /etc/pacman.d/gnupg/S.gpg-agent 3974443               * 0                    
u_str  LISTEN     0      5      /etc/pacman.d/gnupg/S.gpg-agent.extra 3974445               * 0                    
u_str  LISTEN     0      50     /tmp/7e70e4acd57e811d3ab0b93cac64694a-{87A94AB0-E370-4cde-98D3-ACC110C5967D} 4402002               * 0                    
u_str  LISTEN     0      5      /run/user/1000/gnupg/S.gpg-agent 3851101               * 0                    
u_str  LISTEN     0      128    /tmp/tmux-1000/default 4068930               * 0                    
u_str  LISTEN     0      5      /run/user/1000/gnupg/S.gpg-agent.extra 3851103               * 0                    
u_str  LISTEN     0      5      /run/user/1000/gnupg/S.gpg-agent.browser 3851105               * 0                    
u_str  LISTEN     0      5      /tmp/.org.chromium.Chromium.tvSafr/SingletonSocket 4992492               * 0                    
u_str  LISTEN     0      5      /run/user/1000/gnupg/S.gpg-agent.ssh 3851107               * 0                    
u_str  LISTEN     0      128    /run/user/1000/keyring/control 22887                 * 0                    
u_str  LISTEN     0      5      /run/cups/cups.sock 12654                 * 0                    
u_str  LISTEN     0      10     /run/NetworkManager/private-dhcp 12172                 * 0                    
u_str  LISTEN     0      5      /etc/pacman.d/gnupg/S.dirmngr 4012384               * 0                    
u_str  LISTEN     0      128    /tmp/ssh-qyVIz6xS5rgO/agent.1804 6281251               * 0                    
u_str  LISTEN     0      128    /run/dbus/system_bus_socket 10896                 * 0                    
u_str  LISTEN     0      128    /run/user/1000/keyring/ssh 22930                 * 0                    
u_str  LISTEN     0      128    /run/user/1000/keyring/pkcs11 22933                 * 0                    
u_seq  LISTEN     0      0      /run/udev/control 8626                  * 0                    
u_str  LISTEN     0      128    @/tmp/dbus-w73zs4Ntdu 22910                 * 0                    
u_str  LISTEN     0      5      /run/user/1000/pulse/native 23503                 * 0                    
u_str  LISTEN     0      5      /etc/pacman.d/gnupg/S.gpg-agent.browser 3974446               * 0                    
u_str  LISTEN     0      5      /etc/pacman.d/gnupg/S.gpg-agent.ssh 3974447               * 0                    
u_str  LISTEN     0      5      /etc/pacman.d/gnupg/S.scdaemon 3974476               * 0                    
u_str  LISTEN     0      128    /run/avahi-daemon/socket 12503                 * 0                    
u_str  LISTEN     0      10     /var/run/acpid.socket 12262                 * 0                    
u_str  LISTEN     0      5      /run/user/1000/gnupg/S.dirmngr 3851510               * 0                    
u_str  LISTEN     0      5      /home/lerax/.dropbox/iface_socket 24657                 * 0                    
u_dgr  UNCONN     0      0       * 22267                 * 12329                
u_dgr  UNCONN     0      0       * 4252891               * 12329                
u_dgr  UNCONN     0      0       * 12155                 * 12329                
u_dgr  UNCONN     0      0       * 8682                  * 8681                 
u_dgr  UNCONN     0      0       * 12569                 * 12329                
u_dgr  UNCONN     0      0       * 8681                  * 8682                 
u_dgr  UNCONN     0      0       * 2001402               * 12329                
u_dgr  UNCONN     0      0       * 12480                 * 12329                
u_dgr  UNCONN     0      0       * 12497                 * 12329                
u_dgr  UNCONN     0      0       * 12235                 * 12329                
u_dgr  UNCONN     0      0       * 12415                 * 12329                
u_dgr  UNCONN     0      0       * 4169450               * 12329                
u_dgr  UNCONN     0      0       * 23229                 * 12329                
u_dgr  UNCONN     0      0       * 12144                 * 12329                
u_dgr  UNCONN     0      0       * 22883                 * 12329                
```

**Comment by npostavs** [comment]
Hmm, I'm afraid I have no idea what that `netstat` error means.

Continuing with the `ss` output, what do you get from
```sh
ss --no-header --listening --family=unix | 
  awk '$5 ~ /(agent[.][0-9]+|ssh)$/{print $5}' | 
  while read socket ; do
     printf '%s: ' $socket
     SSH_AUTH_SOCK=$socket ssh-add -l
  done
```

**Comment by ryukinix** [comment]
```
❯ ss --no-header --listening --family=unix |
  awk '$5 ~ /(agent[.][0-9]+|ssh)$/{print $5}' |
  while read socket ; do
     printf '%s: ' $socket
     SSH_AUTH_SOCK=$socket ssh-add -l
  done
/run/user/1000/keyring/ssh: 4096 SHA256:iI4pMLmxlIthMP+JaZyy78QQlqwRqYlAwr6km02ru/4 manoel_vilela@engineer.com (RSA)

```

**Comment by ryukinix** [comment]
Inside of emacs too:
```
% ss --no-header --listening --family=unix |                                                                                                                   
  awk '$5 ~ /(agent[.][0-9]+|ssh)$/{print $5}' |                                                                                                               
  while read socket ; do                                                                                                                                       
     printf '%s: ' $socket                                                                                                                                     
     SSH_AUTH_SOCK=$socket ssh-add -l                                                                                                                          
  done                                                                                                                                                         
ss --no-header --listening --family=unix |                                                                                                                     
>   awk '$5 ~ /(agent[.][0-9]+|ssh)$/{print $5}' |                                                                                                             
>   while read socket ; do                                                                                                                                     
>      printf '%s: ' $socket                                                                                                                                   
>      SSH_AUTH_SOCK=$socket ssh-add -l                                                                                                                        
>   done                                                                                                                                                       
/run/user/1000/keyring/ssh: 4096 SHA256:iI4pMLmxlIthMP+JaZyy78QQlqwRqYlAwr6km02ru/4 manoel_vilela@engineer.com (RSA)    
```

**Comment by ryukinix** [comment]
Maybe I just setup wrong the new version? Just to you be sure: my steps to testing was just disabling my old scripts, start emacs, `C-x C-b` on the buffer with a new version of ssh-agency and made tests.

Maybe I'm wrongly executing the old defintions of symbols and functions? I'll replace the ELPA installed  file for your PR version to be sure.

**Comment by ryukinix** [comment]
![image](https://user-images.githubusercontent.com/7642878/31869760-88934dd4-b780-11e7-9f35-7ebf9ca3e023.png)

Did that, but nothing changes. So probably I don't mess up earlier on re-eval.

**Comment by ryukinix** [comment]
BUT, and the `.elc` files? D: I forgot to delete them... I need?

**Comment by ryukinix** [comment]
There is a better way to override a installation of package instead of copying manually to the elpa installed version? (sorry for asking that)

**Comment by npostavs** [comment]
In theory the elisp code should be doing the same as the shell code I gave you. Oh, except I should have said `ss --no-header --listening --family=unix src '*ssh*' | ...`, should make no difference though.

If you evaluate
```elisp
(ssh-agency-find-socket-from-ss
 :glob "*ssh*"
 :regexp ssh-agency-socket-regexp)
```
do you not get `/run/user/1000/keyring/ssh`?

> There is a better way to override a installation of package instead of copying manually to the elpa installed version? (sorry for asking that)

For a single-file package like ssh-agency, it should be enough to do `M-x load-file path/to/new/ssh-agency.el`. In general, you can put the new package location earlier in `load-path`.

**Comment by ryukinix** [comment]
For me: 
```emacs-lisp
 (ssh-agency-find-socket-from-ss
 :glob "*ssh*"
 :regexp ssh-agency-socket-regexp) ;; => "/tmp/ssh-rxS4Iax3gNTH/agent.5308"
```
Maybe ssh-agency is creating the SSH_AUTH_SOCK + SSH_AGENT before searching for a new one?

> For a single-file package like ssh-agency, it should be enough to do M-x load-file path/to/new/ssh-agency.el. In general, you can put the new package location earlier in load-path.
Thank you for sharing that.

**Comment by ryukinix** [comment]
> In theory the elisp code should be doing the same as the shell code I gave you. Oh, except I should have said ss --no-header --listening --family=unix src '*ssh*' | ..., should make no difference though.

```
❯ ss --no-header --listening --family=unix src '*ssh*'
u_str  LISTEN     0      128    /tmp/ssh-rxS4Iax3gNTH/agent.5308 46087                 * 0                    
u_str  LISTEN     0      128    /tmp/ssh-7PCnid07kX0H/agent.5947 65497                 * 0                    
u_str  LISTEN     0      128    /run/user/1000/keyring/ssh 13250 
```

**Comment by npostavs** [comment]
Are those extra ssh-agents created from earlier ssh-agency calls? If you kill them, does the `ssh-agency-find-socket-from-ss` call then give you `/run/user/1000/keyring/ssh`?

**Comment by ryukinix** [comment]
> Are those extra ssh-agents created from earlier ssh-agency calls? If you kill them, does the ssh-agency-find-socket-from-ss call then give you /run/user/1000/keyring/ssh?

Yes.
```
(ssh-agency-find-socket-from-ss
 :glob "*ssh*"
 :regexp ssh-agency-socket-regexp)
"/run/user/1000/keyring/ssh"
```

**Comment by ryukinix** [comment]
But after executing `(ssh-agency-ensure)` again I got:

```
(ssh-agency-status)
no-keys

(ssh-agency-ensure)
1


(ssh-agency-find-socket-from-ss
 :glob "*ssh*"
 :regexp ssh-agency-socket-regexp)
"/tmp/ssh-P8r7nnK8BHKF/agent.17394"
```

**Comment by ryukinix** [comment]
Seems that (ssh-agency-ensure) is the problem.

**Comment by npostavs** [comment]
> Seems that ssh-agency-ensure is the problem (or something that is called inside it)

Oh! There is a silly bug in it. Not sure how I missed that before. Maybe because I tested with 0 agents running initially. Should be fixed now.

**Comment by ryukinix** [comment]
~ testing it ~

**Comment by ryukinix** [comment]
![image](https://user-images.githubusercontent.com/7642878/31899055-06514378-b7f1-11e7-9d6b-2ad233e822fa.png)

Seems that we are missing something yet.

**Comment by ryukinix** [comment]
Maybe this is occurring because I don't have more `ssh-agent` process running and `ssh-agency-ensure` create one even if a ssh socket is found. 

Even if I don't have `ssh-agent` running, still works because gnome-keyring-daemon probably provide a agent as we discussed

**Comment by ryukinix** [comment]
So, if a socket for ssh is created, this should enough information that are a kind of ssh agent running? If that so, we can cut the exigency for running another `ssh-agent` when another is not found.

**Comment by npostavs** [comment]
After killing any extra ssh-agents, does ` (ssh-agency-find-agent)` not find the gnome keyring daemon?

**Comment by ryukinix** [comment]
Wait a moment, I will test it.

**Comment by ryukinix** [comment]
```
(ssh-agency-find-agent)
nil
```
This is the result on a fresh session

**Comment by npostavs** [comment]
Hmm, what do you get from `pgrep -a gnome-keyring-daemon`? If nothing, can you find the right name?

**Comment by ryukinix** [comment]
And my ssh authentication on terminal is fine... I should able to auth ssh login on my vps servers, clone private repos with ssh... and so on.

**Comment by ryukinix** [comment]
I have a complete strange behavior here:
```
~/Desktop
❯ pgrep gnome-keyring-daemon

~/Desktop
❯ pgrep gnome-keyring-d -a
2706 /usr/bin/gnome-keyring-daemon --daemonize --login

```

I just doesn't understand that  :( sorry

**Comment by ryukinix** [comment]
Why `gnome-keyring-d`?

**Comment by ryukinix** [comment]
ARRRRHHG
```
/proc/2706
❯ cat cmdline
/usr/bin/gnome-keyring-daemon--daemonize--login
/proc/2706
❯ cat comm
gnome-keyring-d
```

That gnome guyes....

**Comment by ryukinix** [comment]
I don't believe it!

**Comment by npostavs** [comment]
Okay, so if you change `"gnome-keyring-daemon"` to `"gnome-keyring-d"` in `ssh-agency-find-agent` it should work.

Is `/usr/bin/gnome-keyring-daemon` a symlink then?

**Comment by ryukinix** [comment]
> Okay, so if you change "gnome-keyring-daemon" to "gnome-keyring-d" in ssh-agency-find-agent it should work.

That was I thought, so I did that before you said. But doesn't works yet :(

> Is /usr/bin/gnome-keyring-daemon a symlink then?

Actually no, 
![image](https://user-images.githubusercontent.com/7642878/31900212-181b1d6a-b7f4-11e7-8a46-e18f314945f7.png)

**Comment by npostavs** [comment]
Hmm, can you look for the equivalent in the return of `(list-system-process)`?

**Comment by ryukinix** [comment]
Seems that is pretty the same:
```
(let ((keys '(comm user))
      (proc (process-attributes 2706)))
  (cl-loop for k in keys collect (assoc k proc)))
((comm . "gnome-keyring-d") (user . "lerax"))
```

**Comment by npostavs** [comment]
Seems like it should be working then, could you try stepping through `ssh-agency-find-agent` with edebug and see where it fails?

**Comment by ryukinix** [comment]
I don't undestand that part:
```
(pid
          (--first (-let (((&alist 'comm comm 'user user) (process-attributes it)))
                     (and (member comm ssh-agent-exe)
                          (string= user user-login-name)))
                   (list-system-processes)))
```
What is `it`?

**Comment by npostavs** [comment]
The process, that code should be equivalent to this:
```elisp
(cl-some (lambda (it)
           (-let (((&alist 'comm comm 'user user) (process-attributes it)))
             (and (member comm ssh-agent-exe)
                  (string= user user-login-name))))
         (list-system-processes))
```

**Comment by ryukinix** [comment]
Thanks for explaining it for me. I used `edebug` and I find that I forgot to kill one of the `ssh-agent`. After that ssh-agency-find-agent would be able to find `gnome-keyring-d`.

**Comment by ryukinix** [comment]
So I think we need to change `gnome-keyring-daemon` to `gnome-keyring-d`.
