### ISSUE TITLE
SSH password is asked for https remotes

### ISSUE THREAD

**Issue by ItsHoff** [magit/ssh-agency#16]
ssh-agency is ran regardless whether using ssh or https remote. I'd like to see ssh-agency ignore operations with https remotes.

**Comment by npostavs** [comment]
Is there a straightforward way to test what the remote type is? Especially with features like [`url.<base>.insteadOf`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-urlltbasegtinsteadOf) (and maybe some others in the future), I don't think just parsing the config file is good enough.

**Comment by tarsius** [comment]
> Is there a straightforward way to test what the remote type is?

If someone answers that question, I might be willing/able to do something about this.
