### ISSUE TITLE
Advising lower level magit-start-process instead of magit-{fetch,pull,push}-{all,current,...}

### ISSUE THREAD

**Issue by npostavs** [magit/ssh-agency#3]
I sometimes use `:` (`magit-git-command`) with a git alias to fetch pull requests from a github repo. Since this isn't one of the `magit-fetch*` commands, ssh-agency doesn't catch it*. Therefore, I'm looking again at my earlier idea I posted at https://github.com/magit/magit/pull/1911#issuecomment-115291551:

> Maybe it's better to advise magit-start-process and check the args for "push", "pull", or "fetch"?

However, @tarsius said

> I don't think that's a good idea.

Could you elaborate?

---

<sub>
*I could instead use the approach described [here](http://emacs.stackexchange.com/questions/13625/viewing-github-prs-in-magit-2-1-0), and then use the normal fetching commands, but I prefer that `--prune` remove the refs. Another example is pushing multiple branches at once.
</sub>

**Comment by tarsius** [comment]
It just felt unclean to patch low-level functions for this. But I cannot really think of a better approach, so you should probably do this for now. I just hope that a cleaner approach emerges over time.

Oh wait! What about using the hook and moving this up one level, i.e. add this to `magit-git-command{,-toplevel}`:

```lisp
(when (member (car args) '("push" "pull" "fetch"))
  (run-hooks 'magit-credential-hook))
```

?

**Comment by npostavs** [comment]
> add this to magit-git-command{,-toplevel}:

Makes sense. Possibly replace `("push" "pull" "fetch")` with a defcustom so the user's aliases can be added too.

---

All this wrestling with the credential helpers has given me another idea: we could put a little shell function which runs `magit-credential-hook` via emacsclient as the first value of `credential.helper`. 

Except I can't see a way to insert ourselves as the first value (`-c credential.help=foo` puts it at the end). Otherwise it seems ideal. :/

**Comment by tarsius** [comment]
Get the values of `credential.help`, unset its values`, and the reset the values starting with ours.

That script would obviously have to check whether it is running "inside" Emacs and otherwise do nothing.

I am not sure this is a good idea - seems fragile - at least it's not my idea of "ideal" :-)

**Comment by tarsius** [comment]
But might be worth trying it out at least.

**Comment by npostavs** [comment]
> I am not sure this is a good idea - seems fragile - at least it's not my idea of "ideal" :-)

I say "ideal" because it would run exactly when git requires credentials, and if I read [git-credential][1] right, we could even know the protocol, allowing e.g. to only trigger the ssh-agent when the remote is using ssh.

> Get the values of credential.help, unset its values`, and the reset the values starting with ours.

But changing the user's config is not very nice. :(

[1]: https://www.kernel.org/pub/software/scm/git/docs/git-credential.html

**Comment by tarsius** [comment]
Ah, sorry I thought that's what you suggested, I didn't notice the `-c`. Now that you have pointed that out I agree that this would be very nice :-)

**Comment by npostavs** [comment]
> Now that you have pointed that out I agree that this would be very nice :-)

Or would have been, if `-c` could be used to prepend (rather than append) a config value :-(

**Comment by tarsius** [comment]
You should be able to use `magit-credential-hook` now.
